services:
  - type: web
    name: vercel-collector
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:render
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.10.0
      - key: NODE_ENV
        value: production
